function [] = PlotterTrace(QD_num, QD_size, dir_name, bin_size)
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Подрограмма для построения Траектории квантовой точки (разбинировано по
% 10 мс) и гистограммы плотности интенсивности. 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Подгружаем данные. 
load(['results/' dir_name 'QD_' QD_num '_' QD_size ...
      'nm/data_files/QD_' QD_num '_' QD_size '_nm_binned_data']);
load(['results/' dir_name 'QD_' QD_num '_' QD_size ...
        'nm/data_files/QD_' QD_num '_' QD_size '_nm_parsed_data']);

% Форматирование данных 
intensity = binned_data.intensity;
arrivals  = parsed_data.arrivals;
arrivals  = 1e-12 * arrivals;

% Настройки полотна
trace_figure = figure('Color', 'white', ...
                      'Units', 'normalized', ...
                      'Name', 'Trace', ...
                      'Visible', 'off', ...
                      'Position', [0.15 0.15 0.7 0.7] ...
                      );

% Непосредственное построение траектории
edges = arrivals(1) : bin_size : arrivals(end);
plot(edges, intensity, 'k-');

% Настройки отображения графика
xlabel('Time [s]', 'FontSize', 24);
ylabel(['Intensity [counts/' num2str(bin_size*1000) ' ms]'], 'FontSize', 24);
set(gca, 'YLim', [0 1.03*max(intensity)], ...
         'XLim', [0 arrivals(end)], ...
         'FontSize', 24 ...
         );
text(0.7, 0.92, [QD_num ' QD ' QD_size ' nm'], ...
    'FontSize', 24, ...
    'Color', 'black', ...
    'Units', 'normalized' ...
    );

% Сохранение
saveas(trace_figure, ['results/' dir_name 'QD_' QD_num '_' QD_size ...
        'nm/images/QD_' QD_num '_' QD_size '_trace_plot.png']);

% Полотно для гистограммы 
trace_hist_figure = figure('Color', 'white', ...
                           'Units', 'normalized', ...
                           'Name', 'Trace', ...
                           'Visible', 'off', ...
                           'Position', [0.15 0.15 0.7 0.7] ...
                           );

% % [occurence, intensity_hist] = ...
% %     hist(intensity, min(intensity):max(intensity));
% % bar(intensity_hist, occurence, ...
% %     'EdgeColor', 'none', ...
% %     'FaceColor', 'k', ...
% %     'FaceAlpha', 1 ...
% %     );
histogram(intensity, min(intensity):max(intensity), ...
          'EdgeColor', 'none', ...
          'FaceColor', 'k', ...
          'FaceAlpha', 1 ...
          );
set(gca, ...
    'XLim', [0 max(intensity)], ...
    'FontSize', 24 ...
    );

% Насройки подписей
xlabel(['Intensity [counts/' num2str(bin_size*1000) ' ms]'], 'FontSize', 24);
ylabel('Occurence', 'FontSize', 24);
text(0.7, 0.92, [QD_num ' QD ' QD_size ' nm'], ...
    'FontSize', 24, ...
    'Color', 'black', ...
    'Units', 'normalized' ...
    );

% Сохранение
saveas(trace_hist_figure, ['results/' dir_name 'QD_' QD_num '_' QD_size ...
        'nm/images/QD_' QD_num '_' QD_size '_trace_hist.png']);
end