function [] = PlotterNewFLID(QD_num, QD_size, dir_name)
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
load(['results/' dir_name 'QD_' QD_num '_' QD_size ...
        'nm/data_files/QD_' QD_num '_' QD_size '_nm_FLID_data']);

lifetime = FLID_data.lifetime;
inten_short = FLID_data.inten_short;
inten_long = FLID_data.inten_long;

NewFLID_figure = figure( ...
    'Name', 'New FLID diagram', ...
    'Color', 'white', ...
    'Units', 'normalized', ...
    'Visible', 'off', ...
    'Position', [0.02 0.02 0.95 0.95] ...
    );
hist3([ [0 lifetime]' [0 inten_long+inten_short]'], [175 175]);
view(2);
ylabel('Short yield', 'Color', 'k', 'FontSize', 24);
xlabel('Fast time [ns]', 'Units', 'normalized', 'FontSize', 24);
set(gca, ...
    'FontSize', 24, ...
    'Color', [0 0 0.49], ...
    'xcolor', 'k', ...
    'ycolor', 'k' ...
    );
set(get(gca, 'child'), ...
    'FaceColor', 'interp', ...
    'EdgeColor', 'none', ...
    'CDataMode', 'auto' ...
    );

colormap parula
cmap = colormap;
cmap(1, :) = [0 0 0.49];
colormap(cmap);
cb = colorbar('location', 'east', 'Color', 'w');
cb.Label.String = 'Occurence';
cb.Label.Interpreter = 'latex';
cb.Label.FontSize = 24;
cb.TickLabelInterpreter = 'latex';

saveas(NewFLID_figure, ['results/' dir_name 'QD_' QD_num '_' QD_size ...
        'nm/images/QD_' QD_num '_' QD_size 'nm_NewFLID_diagram.png']);

end

