function [] = PlotterFLID(QD_num, QD_size, dir_name)
set(groot, 'defaultAxesTickLabelInterpreter', 'latex');
set(groot, 'defaultTextInterpreter', 'latex');
set(groot, 'defaultLegendInterpreter', 'latex');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
load(['results/' dir_name 'QD_' QD_num '_' QD_size ...
        'nm/data_files/QD_' QD_num '_' QD_size '_nm_binned_data']);

load(['results/' dir_name 'QD_' QD_num '_' QD_size ...
        'nm/data_files/QD_' QD_num '_' QD_size '_nm_FLID_data']);

lifetime    = FLID_data.lifetime;
dec_time2   = FLID_data.dec_time2;
right_time  = FLID_data.right_time;
inten_short = FLID_data.inten_short;
inten_long  = FLID_data.inten_long;

fg = figure( ...
    'Color', 'white', ...
    'Units', 'normalized', ...
    'Position', [0.02 0.02 0.95 0.95] ...
    );

colormap parula
axis([0 30 0 300]);
cmap = colormap;
cmap(1, :) = [0 0 0.49];
colormap(cmap)
cb = colorbar('location', 'east', 'Color', 'w');
cb.Label.String = 'Occurence';
cb.Label.Interpreter = 'latex';
cb.Label.FontSize = 24;
cb.TickLabelInterpreter = 'latex';

FLID_figure = figure( ...
                'Color', 'white', ...
                'Units', 'normalized', ...
                'Position', [0.02 0.02 0.95 0.95] ...
                );

hist3([[0 lifetime]' [0 inten_long+inten_short]'/max(inten_long + inten_short)], ...
    [175 175]);
set(get(gca, 'child'), ...
    'FaceColor', 'interp', ...
    'CDataMode', 'auto', ...
    'EdgeColor', 'none' ...
    );
view(2);
ylabel('Short yield', 'Color', 'k', 'FontSize', 24);
xlabel('Fast time [ns]', 'Units', 'normalized', 'FontSize', 24);
set(gca, ...
    'FontSize', 24, ...
    'Color', [0 0 0.49], ...
    'xcolor', 'k', ...
    'ycolor', 'k' ...
    );
colormap parula
cmap(1, :) = [0 0 0.49];
colormap(cmap);
cb = colorbar('location', 'east', 'Color', 'w');
cb.Label.String = 'Occurence';
cb.Label.Interpreter = 'latex';
cb.Label.FontSize = 24;
cb.TickLabelInterpreter = 'latex';

saveas(FLID_figure, ['results/' dir_name 'QD_' QD_num '_' QD_size ...
        'nm/images/QD_' QD_num '_' QD_size '_FLID_new.png']);
end